#!/bin/bash

# شعار RedSaléOps
clear
echo -e "\e[1;31m"
echo "  █████╗ ███╗   ██╗ █████╗ ███████╗██╗  ██╗██╗   ██╗███╗   ██╗████████╗███████╗██████╗ "
echo " ██╔══██╗████╗  ██║██╔══██╗██╔════╝██║  ██║██║   ██║████╗  ██║╚══██╔══╝██╔════╝██╔══██╗"
echo " ███████║██╔██╗ ██║███████║███████╗███████║██║   ██║██╔██╗ ██║   ██║   █████╗  ██████╔╝				Anass Labrini"
echo " ██╔══██║██║╚██╗██║██╔══██║╚════██║██╔══██║██║   ██║██║╚██╗██║   ██║   ██╔══╝  ██╔══██╗"
echo " ██║  ██║██║ ╚████║██║  ██║███████║██║  ██║╚██████╔╝██║ ╚████║   ██║   ███████╗██║  ██║"
echo " ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝"
                                                                                      
echo -e "\e[0m"

# المسار الكامل للمجلد الحالي
script_dir=$(dirname "$(realpath "$0")")

# القائمة
echo -e "\e[1;32m  1) SQL Injection Scanner"
echo -e "  2) XSS Vulnerability Scanner"
echo -e "  3) Clickjacking Detector"
echo -e "  4) Brute Force Attack Tool"
echo -e "  5) DDoS Simulation Tool"
echo -e "  6) Exit \e[0m"
echo ""
echo ""

read -e -p $'\e[1;32mSelect attack number: \e[0m' choice
echo ""

case $choice in
    1)
        python3 "$script_dir/sqli/sqli.py"
        ;;
    2)
        python3 "$script_dir/xss/xss.py"
        ;;
    3)
        python3 "$script_dir/clickjacking/clickjacking.py"
        ;;
    4)
        python3 "$script_dir/bruteforce/bruteforce.py"
        ;;
    5)
        python3 "$script_dir/dos/dos.py"
        ;;
    6)
        echo "Close script..."
        exit 0
        ;;
    *)
        echo "Invalid option, please choose a correct number."
        ;;
esac


# المسار الكامل للمجلد الحالي
script_dir=$(dirname "$(realpath "$0")")

# القائمة
echo -e "  1) SQL Injection Scanner"
echo -e "  2) XSS Vulnerability Scanner"
echo -e "  3) Clickjacking Detector"
echo -e "  4) Brute Force Attack Tool"
echo -e "  5) DoS Simulation Tool"
echo -e "  6) Exit "
echo ""
echo ""

read -e -p $'Select attack number: ' choice
echo ""

case $choice in
    1)
        python3 "$script_dir/sqli/sqli.py"
        ;;
    2)
        python3 "$script_dir/xss/xss.py"
        ;;
    3)
        python3 "$script_dir/clickjacking/clickjacking.py"
        ;;
    4)
        python3 "$script_dir/bruteforce/bruteforce.py"
        ;;
    5)
        python3 "$script_dir/dos/dos.py"
        ;;
    6)
        echo "Close script..."
        exit 0
        ;;
    *)
        echo "Invalid option, please choose a correct number."
        ;;
esac
